package com.bookshop.mybookshop.domain;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.ToString;
import org.hibernate.annotations.ColumnDefault;

import javax.persistence.CollectionTable;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import java.sql.Blob;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

@Data
@ToString(exclude = "id")
@Entity(name = "books")
@ApiModel(description = "entity representing a book")
public class Book {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("id generated by DB automatically")
    private Integer id;

    @JsonIgnore
    @ManyToMany(mappedBy = "books")
    private List<Author> authors = new ArrayList<>();

    @Column(nullable = false)
    @ApiModelProperty("book title")
    private String title;

    @Column(nullable = false)
    @ApiModelProperty("mnemonical identity sequence of characters")
    private String slug;

    @Column(name = "pub_date", nullable = false)
    @ApiModelProperty("book publication date")
    private LocalDateTime publicationDate;

    @Column(nullable = false)
    @ColumnDefault("0")
    @ApiModelProperty("book discount in %")
    private Integer discount;

    @Column(nullable = false)
    @ApiModelProperty("book price")
    private Integer price;

    @CollectionTable(name = "books_genres",
            joinColumns = @JoinColumn(name = "book_id"))
    @Column(name = "genre", nullable = false)
    @Enumerated(EnumType.STRING)
    @ElementCollection(targetClass = Genre.class)
    @ApiModelProperty("book genres")
    private List<Genre> genres = new ArrayList<>();

    @ApiModelProperty("book description")
    private String description;

    @ApiModelProperty("image url")
    private String image;

    @CollectionTable(name = "books_tags",
            joinColumns = @JoinColumn(name = "book_id"))
    @Column(name = "tag", nullable = false)
    @Enumerated(EnumType.STRING)
    @ElementCollection(targetClass = BookTag.class)
    @ApiModelProperty("book tags")
    private Set<BookTag> bookTags = new HashSet<>();

    @OneToMany(mappedBy = "book")
    @ApiModelProperty("book reviews")
    private List<Review> reviews = new ArrayList<>();

    @Column(name = "is_bestseller")
    @ApiModelProperty("is bestseller or not (boolean)")
    private Boolean isBestseller;

    @ManyToMany
    @JoinTable(
            name = "books_users",
            joinColumns = @JoinColumn(name = "book_id", nullable = false),
            inverseJoinColumns = @JoinColumn(name = "user_id", nullable = false)
    )
    @ApiModelProperty("list of users who")
    private List<User> users = new ArrayList<>();

    @Enumerated(EnumType.STRING)
    @ApiModelProperty("book status")
    private BookStatus status;

    @OneToMany(mappedBy = "book")
    @ApiModelProperty("list of transaction with this book")
    private List<BalanceTransaction> transactions = new ArrayList<>();

}
