insert into books (id, price, discount, title, slug, pub_date, description, is_bestseller) values (1, 563, 32, 'Singh Is Kinng', 'Syrup', '2020-07-09 22:56:39', 'accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris', false);
insert into books (id, price, discount, title, slug, pub_date, description, is_bestseller) values (2, 885, 22, 'God of Cookery (Sik san)', 'Green Street Hooligans (a.k.a. Hooligans)', '2020-06-29 04:10:02', 'ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis', true);
insert into books (id, price, discount, title, slug, pub_date, description, is_bestseller) values (3, 690, 25, 'Travellers and Magicians', 'Spare Bed-Room', '2020-10-06 00:11:07', 'sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie', true);
insert into books (id, price, discount, title, slug, pub_date, description, is_bestseller) values (4, 419, 36, 'Inside: ''Dr. Strangelove or How I Learned to Stop Worrying and Love the Bomb''', 'Best Man, The', '2020-10-01 01:31:30', 'donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus', false);
insert into books (id, price, discount, title, slug, pub_date, description, is_bestseller) values (5, 798, 29, 'It Started in Naples', 'Dawn of the Dead', '2020-02-11 23:14:24', 'rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl', true);
insert into books (id, price, discount, title, slug, pub_date, description, is_bestseller) values (6, 481, 31, 'Riddick', 'Rage (Rabia)', '2020-10-17 01:48:18', 'amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed', false);
insert into books (id, price, discount, title, slug, pub_date, description, is_bestseller) values (7, 761, 33, 'Confess', 'Crawling Eye, The (a.k.a. Trollenberg Terror, The)', '2020-06-09 09:18:00', 'nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla', false);
insert into books (id, price, discount, title, slug, pub_date, description, is_bestseller) values (8, 868, 22, 'Shout, The', 'Miracle in Cell No. 7', '2020-07-16 12:42:57', 'posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis', true);
insert into books (id, price, discount, title, slug, pub_date, description, is_bestseller) values (9, 861, 43, 'Look Who''s Talking Too', 'Stand Up Guys', '2020-05-11 01:12:01', 'penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor', true);
insert into books (id, price, discount, title, slug, pub_date, description, is_bestseller) values (10, 879, 24, 'Kickboxer 3: The Art of War (Kickboxer III: The Art of War)', 'What''s Up, Scarlet?', '2020-04-13 22:47:14', 'justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices', true);
insert into books (id, price, discount, title, slug, pub_date, description, is_bestseller) values (11, 719, 22, 'Reel Bad Arabs: How Hollywood Vilifies a People', 'Drones', '2020-09-04 07:23:10', 'sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede', true);
insert into books (id, price, discount, title, slug, pub_date, description, is_bestseller) values (12, 425, 12, 'Battle of China, The (Why We Fight, 6)', 'Hitchhiker''s Guide to the Galaxy, The', '2020-03-27 16:55:25', 'ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas', false);
insert into books (id, price, discount, title, slug, pub_date, description, is_bestseller) values (13, 384, 34, 'Bluebeard', 'No Logo', '2020-05-19 19:24:01', 'ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat', true);
insert into books (id, price, discount, title, slug, pub_date, description, is_bestseller) values (14, 484, 29, 'Androcles and the Lion', 'Leviathan', '2020-07-29 12:51:49', 'praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante', false);
insert into books (id, price, discount, title, slug, pub_date, description, is_bestseller) values (15, 909, 26, 'A Mulher Invisível', 'Desi Boyz', '2020-10-18 09:13:13', 'in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non', false);
insert into books (id, price, discount, title, slug, pub_date, description, is_bestseller) values (16, 812, 42, 'Redemption: The Stan Tookie Williams Story', 'Into the Deep', '2020-05-04 22:01:01', 'pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra', false);
insert into books (id, price, discount, title, slug, pub_date, description, is_bestseller) values (17, 616, 16, 'To Begin Again (a.k.a. Starting Over) (Volver a Empezar)', 'Lathe of Heaven, The', '2020-07-22 12:28:09', 'mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla', false);
insert into books (id, price, discount, title, slug, pub_date, description, is_bestseller) values (18, 653, 8, 'Code of Silence', 'Whole Ten Yards, The', '2020-08-11 14:23:43', 'non quam nec dui luctus rutrum nulla tellus in sagittis dui', true);
insert into books (id, price, discount, title, slug, pub_date, description, is_bestseller) values (19, 788, 12, 'Nine', 'Recipe for Love', '2020-10-13 22:02:10', 'metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit', true);
insert into books (id, price, discount, title, slug, pub_date, description, is_bestseller) values (20, 344, 6, 'Into the Mind', 'Where the Boys Are ''84', '2020-09-15 07:26:14', 'ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus', false);



insert into authors (id, first_name, last_name, biography, slug, description) values (1, 'Mable', 'Sparkwill', 'pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut', 'ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi', 'nam congue risus semper porta volutpat quam pede lobortis ligula sit');
insert into authors (id, first_name, last_name, biography, slug, description) values (2, 'Mirabelle', 'Graddell', 'at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel', 'luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida', 'metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec');
insert into authors (id, first_name, last_name, biography, slug, description) values (3, 'Lonny', 'Alfonsini', 'nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum', 'tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo', 'at turpis donec posuere metus vitae ipsum aliquam non mauris');
insert into authors (id, first_name, last_name, biography, slug, description) values (4, 'Georgi', 'Ellingsworth', 'lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt', 'proin eu mi nulla ac enim in tempor turpis nec', 'erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt');
insert into authors (id, first_name, last_name, biography, slug, description) values (5, 'Jamaal', 'Pentland', 'feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id', 'aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet', 'nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo');
insert into authors (id, first_name, last_name, biography, slug, description) values (6, 'Dido', 'Castanie', 'pede lobortis ligula sit amet eleifend pede libero quis orci', 'blandit non interdum in ante vestibulum ante ipsum primis in faucibus', 'amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus');
insert into authors (id, first_name, last_name, biography, slug, description) values (7, 'Hendrika', 'Alders', 'bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce', 'congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl', 'ut tellus nulla ut erat id mauris vulputate elementum nullam');
insert into authors (id, first_name, last_name, biography, slug, description) values (8, 'Olag', 'Mc Elory', 'tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque', 'duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend', 'praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in');
insert into authors (id, first_name, last_name, biography, slug, description) values (9, 'Hamil', 'Kersting', 'amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in', 'nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis', 'at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget');
insert into authors (id, first_name, last_name, biography, slug, description) values (10, 'Dorothy', 'Yeates', 'morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce', 'magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis', 'praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut');
insert into authors (id, first_name, last_name, biography, slug, description) values (11, 'Rik', 'Shenfisch', 'lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac', 'dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in', 'sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras');
insert into authors (id, first_name, last_name, biography, slug, description) values (12, 'Eloisa', 'Shrive', 'mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit', 'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam', 'aenean sit amet justo morbi ut odio cras mi pede malesuada in');
insert into authors (id, first_name, last_name, biography, slug, description) values (13, 'Michele', 'Riggulsford', 'leo odio porttitor id consequat in consequat ut nulla sed accumsan', 'aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas', 'cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus');
insert into authors (id, first_name, last_name, biography, slug, description) values (14, 'Iosep', 'Vant', 'amet diam in magna bibendum imperdiet nullam orci pede venenatis', 'sit amet nulla quisque arcu libero rutrum ac lobortis vel', 'metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis');
insert into authors (id, first_name, last_name, biography, slug, description) values (15, 'Donall', 'Espinay', 'tellus nulla ut erat id mauris vulputate elementum nullam varius', 'in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis', 'ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus');
insert into authors (id, first_name, last_name, biography, slug, description) values (16, 'Ferdinand', 'Henricsson', 'est phasellus sit amet erat nulla tempus vivamus in felis', 'pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus', 'sit amet eleifend pede libero quis orci nullam molestie nibh');
insert into authors (id, first_name, last_name, biography, slug, description) values (17, 'Ronna', 'Bride', 'mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean', 'praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede', 'ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien');
insert into authors (id, first_name, last_name, biography, slug, description) values (18, 'Pepillo', 'Hallick', 'lectus pellentesque at nulla suspendisse potenti cras in purus eu', 'vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget', 'non mauris morbi non lectus aliquam sit amet diam in magna');
insert into authors (id, first_name, last_name, biography, slug, description) values (19, 'Vivi', 'Bullin', 'donec ut mauris eget massa tempor convallis nulla neque libero convallis eget', 'vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget', 'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia');
insert into authors (id, first_name, last_name, biography, slug, description) values (20, 'Patin', 'Bellringer', 'id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue', 'ipsum dolor sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam', 'vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in');


insert into authors_books (author_id, book_id) values (1, 1);
insert into authors_books (author_id, book_id) values (2, 2);
insert into authors_books (author_id, book_id) values (3, 3);
insert into authors_books (author_id, book_id) values (4, 4);
insert into authors_books (author_id, book_id) values (5, 5);
insert into authors_books (author_id, book_id) values (6, 6);
insert into authors_books (author_id, book_id) values (7, 7);
insert into authors_books (author_id, book_id) values (8, 8);
insert into authors_books (author_id, book_id) values (9, 9);
insert into authors_books (author_id, book_id) values (10, 10);
insert into authors_books (author_id, book_id) values (11, 11);
insert into authors_books (author_id, book_id) values (12, 12);
insert into authors_books (author_id, book_id) values (13, 13);
insert into authors_books (author_id, book_id) values (14, 14);
insert into authors_books (author_id, book_id) values (15, 15);
insert into authors_books (author_id, book_id) values (16, 16);
insert into authors_books (author_id, book_id) values (17, 17);
insert into authors_books (author_id, book_id) values (18, 18);
insert into authors_books (author_id, book_id) values (19, 19);
insert into authors_books (author_id, book_id) values (20, 20);




/*insert into authors (id, first_name, last_name) values (1, 'Shaylah', 'Croy');
insert into authors (id, first_name, last_name) values (2, 'Constantin', 'Howis');
insert into authors (id, first_name, last_name) values (3, 'Yasmeen', 'Vannuccini');
insert into authors (id, first_name, last_name) values (4, 'Silvanus', 'Height');
insert into authors (id, first_name, last_name) values (5, 'Emmey', 'Iacomo');
insert into authors (id, first_name, last_name) values (6, 'Kelby', 'Garter');
insert into authors (id, first_name, last_name) values (7, 'Holly-anne', 'Gittose');
insert into authors (id, first_name, last_name) values (8, 'Mohammed', 'Waddams');
insert into authors (id, first_name, last_name) values (9, 'Charleen', 'Boult');
insert into authors (id, first_name, last_name) values (10, 'Sarette', 'Echalie');
insert into authors (id, first_name, last_name) values (11, 'Lindsay', 'Mardoll');
insert into authors (id, first_name, last_name) values (12, 'Ruthie', 'Van Arsdale');
insert into authors (id, first_name, last_name) values (13, 'Mariele', 'Grigoroni');
insert into authors (id, first_name, last_name) values (14, 'Annice', 'Tabord');
insert into authors (id, first_name, last_name) values (15, 'Dahlia', 'Manvelle');
insert into authors (id, first_name, last_name) values (16, 'Sterne', 'Geyton');
insert into authors (id, first_name, last_name) values (17, 'Crystal', 'McAllen');
insert into authors (id, first_name, last_name) values (18, 'Kendricks', 'Semble');
insert into authors (id, first_name, last_name) values (19, 'Cesare', 'Brader');
insert into authors (id, first_name, last_name) values (20, 'Emelita', 'Jolliff');
insert into authors (id, first_name, last_name) values (21, 'Linell', 'Doget');
insert into authors (id, first_name, last_name) values (22, 'Brade', 'Voules');
insert into authors (id, first_name, last_name) values (23, 'Janel', 'Wardlow');
insert into authors (id, first_name, last_name) values (24, 'Peggie', 'Rapa');
insert into authors (id, first_name, last_name) values (25, 'Ibrahim', 'Clac');
insert into authors (id, first_name, last_name) values (26, 'Kilian', 'Gommowe');
insert into authors (id, first_name, last_name) values (27, 'Editha', 'Wingar');
insert into authors (id, first_name, last_name) values (28, 'Nowell', 'Rome');
insert into authors (id, first_name, last_name) values (29, 'Raimondo', 'Kornel');
insert into authors (id, first_name, last_name) values (30, 'Nev', 'Gilligan');

insert into books (id, price, price_old, title, author_id, genre) values (1, 331, 1007, 'Home Ing', 16, 'LIGHT');
insert into books (id, price, price_old, title, author_id, genre) values (2, 236, 494, 'It', 16, 'LIGHT');
insert into books (id, price, price_old, title, author_id, genre) values (3, 992, 747, 'Holdlamis', 20, 'LIGHT');
insert into books (id, price, price_old, title, author_id, genre) values (4, 582, 874, 'Bytecard', 16, 'LIGHT');
insert into books (id, price, price_old, title, author_id, genre) values (5, 267, 467, 'Holdlamis', 11, 'LIGHT');
insert into books (id, price, price_old, title, author_id, genre) values (6, 292, 1002, 'Aerified', 27, 'LIGHT');
insert into books (id, price, price_old, title, author_id, genre) values (7, 488, 961, 'Stim', 14, 'LIGHT');
insert into books (id, price, price_old, title, author_id, genre) values (8, 617, 634, 'Y-find', 12, 'LIGHT');
insert into books (id, price, price_old, title, author_id, genre) values (9, 496, 715, 'Keylex', 13, 'LIGHT');
insert into books (id, price, price_old, title, author_id, genre) values (10, 529, 951, 'Toughjoyfax', 23, 'SERIOUS');
insert into books (id, price, price_old, title, author_id, genre) values (11, 678, 437, 'Wrapsafe', 14, 'SERIOUS');
insert into books (id, price, price_old, title, author_id, genre) values (12, 737, 797, 'Kanlam', 15, 'SERIOUS');
insert into books (id, price, price_old, title, author_id, genre) values (13, 662, 447, 'Job', 4, 'SERIOUS');
insert into books (id, price, price_old, title, author_id, genre) values (14, 737, 882, 'Sonair', 11, 'SERIOUS');
insert into books (id, price, price_old, title, author_id, genre) values (15, 946, 1091, 'Job', 30, 'SERIOUS');
insert into books (id, price, price_old, title, author_id, genre) values (16, 314, 639, 'Duobam', 3, 'SERIOUS');
insert into books (id, price, price_old, title, author_id, genre) values (17, 706, 694, 'Cardify', 4, 'SERIOUS');
insert into books (id, price, price_old, title, author_id, genre) values (18, 643, 1035, 'Flexidy', 19, 'SERIOUS');
insert into books (id, price, price_old, title, author_id, genre) values (19, 555, 903, 'Aerified', 28, 'SERIOUS');
insert into books (id, price, price_old, title, author_id, genre) values (20, 258, 972, 'Overhold', 19,'SERIOUS');
insert into books (id, price, price_old, title, author_id, genre) values (21, 825, 834, 'Regrant', 29, 'DRAMATURGY');
insert into books (id, price, price_old, title, author_id, genre) values (22, 553, 942, 'Y-Solowarm', 9, 'DRAMATURGY');
insert into books (id, price, price_old, title, author_id, genre) values (23, 429, 465, 'Alpha', 12, 'DRAMATURGY');
insert into books (id, price, price_old, title, author_id, genre) values (24, 671, 638, 'Otcom', 23, 'DRAMATURGY');
insert into books (id, price, price_old, title, author_id, genre) values (25, 724, 728, 'Quo Lux', 18, 'DRAMATURGY');
insert into books (id, price, price_old, title, author_id, genre) values (26, 717, 952, 'It', 10, 'DRAMATURGY');
insert into books (id, price, price_old, title, author_id, genre) values (27, 734, 758, 'Bitchip', 5, 'DRAMATURGY');
insert into books (id, price, price_old, title, author_id, genre) values (28, 733, 1014, 'Lotlux', 9, 'DRAMATURGY');
insert into books (id, price, price_old, title, author_id, genre) values (29, 371, 735, 'Opela', 1, 'DRAMATURGY');
insert into books (id, price, price_old, title, author_id, genre) values (30, 407, 645, 'Ronstring', 29, 'DRAMATURGY');*/